version: '2'
services:
  web:
    container_name: web
    build: .
    ports:
     - 80:80
     - 443:443
    networks:
      - lamp_stack
    stdin_open: true
    tty: true
    networks:
      - lamp_stack
    restart: always
    cap_add:
    - SYS_ADMIN
    command: bash -c 'mount -oremount,rw /sys/fs/cgroup; mkdir /sys/fs/cgroup/systemd; mount -oremount,ro /sys/fs/cgroup; exec /usr/sbin/init'
  db:
    container_name: db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=i
      - MYSQL_DATABASE=db_test
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=i
    networks:
      - lamp_stack
    restart: always
    expose:
      - '3306'
networks:
  lamp_stack:
    driver: 'bridge'
